name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android32
            os: ubuntu-latest
            target: Android32

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      # Este paso instala el SDK para que CMake pueda encontrarlo
      - name: Setup Geode SDK
        uses: geode-sdk/setup-geode@v3.0.0
        with:
          sdk: v5.5.0

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
          sdk: v5.5.0
          combine: true
          
