name: Build Geode Mod
on: [workflow_dispatch, push]

jobs:
  build:
    strategy:
      matrix:
        target: [Android32]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.target }}
          sdk: nightly
          
